import { execSync } from 'child_process';

export function ghIsAuthenticated(): boolean {
  try {
    execSync('gh auth status', { stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

export function createRepo(repoPath: string, description: string): string {
  // repoPath e.g. "acme-corp/acmeui"
  const result = execSync(
    `gh repo create ${repoPath} --public --confirm --description "${description}"`,
    { encoding: 'utf-8' }
  );
  return result.trim();
}

export function initAndPush(localDir: string, repoPath: string, account: string) {
  const remote = `git@github-${account}:${repoPath}.git`;
  const commands = [
    `cd ${localDir} && git init`,
    `cd ${localDir} && git add .`,
    `cd ${localDir} && git commit -m "init: ${repoPath} — generated by SystemSync"`,
    `cd ${localDir} && git remote add origin ${remote}`,
    `cd ${localDir} && git push -u origin main`,
  ];
  for (const cmd of commands) {
    execSync(cmd, { stdio: 'inherit' });
  }
}
