import fs from 'fs';
import path from 'path';
import { SystemSyncAdapter, SystemSyncConfig } from '../types';

export function scaffoldExtension(
  targetDir: string,
  config: SystemSyncConfig,
  adapter: SystemSyncAdapter
) {
  const { extension } = config;
  const tokenStructure = adapter.getTokenStructure();

  // Create directory structure
  const dirs = [
    'src/components',
    'src/component-sets',
    'src/workflows',
    'src/style-tiles',
    'src/views',
    'src/theme',
    '.storybook',
  ];
  for (const dir of dirs) {
    fs.mkdirSync(path.join(targetDir, dir), { recursive: true });
  }

  // tokens.ts
  const spacingCategory  = tokenStructure.categories.find(c => c.name === 'spacing');
  const radiusCategory   = tokenStructure.categories.find(c => c.name === 'radius');
  const spacingTokens    = spacingCategory?.tokens.map(t =>
    `  '${t}': undefined, // fill in your value`).join('\n') || '';
  const radiusTokens     = radiusCategory?.tokens.map(t =>
    `  '${t}': undefined, // fill in your value`).join('\n') || '';

  // suppress unused variable warnings
  void spacingTokens;
  void radiusTokens;

  writeFile(path.join(targetDir, 'src/theme/tokens.ts'), `
// tokens.ts — ${extension.name}
// Generated by SystemSync from the ${extension.source} adapter
//
// Structural tokens (spacing, radius) are inherited from ${extension.source}.
// Fill in your extension's visual tokens below.

import { spacing, radius } from '@neilmenday/stilo';

// Structural tokens — inherited, do not modify
export { spacing, radius };

// Visual tokens — define your extension's values here
export const colors: Record<string, string> = {
  // e.g. primary: '#005FB2',
};

export const typography = {
  fontStack: '', // e.g. "'Inter', sans-serif"
};
`.trim());

  // src/index.ts
  writeFile(path.join(targetDir, 'src/index.ts'),
    `export * from './theme/tokens';\n`);

  // Storybook main.ts
  writeFile(path.join(targetDir, '.storybook/main.ts'), `
import type { StorybookConfig } from '@storybook/react-webpack5';

const config: StorybookConfig = {
  stories: ['../src/**/*.stories.@(ts|tsx)'],
  addons: [
    '@storybook/addon-essentials',
  ],
  framework: {
    name: '@storybook/react-webpack5',
    options: {},
  },
};

export default config;
`.trim());

  // Storybook preview.ts
  writeFile(path.join(targetDir, '.storybook/preview.ts'), `
import type { Preview } from '@storybook/react';

const preview: Preview = {
  parameters: {
    layout: 'centered',
  },
};

export default preview;
`.trim());

  // package.json
  const pkg = {
    name: extension.name.toLowerCase().replace(/\s+/g, '-'),
    version: '0.1.0',
    description: `${extension.name} — a UI extension built on ${extension.source}`,
    scripts: {
      storybook: 'storybook dev -p 6006',
      'build-storybook': 'storybook build',
      typecheck: 'tsc --noEmit',
    },
    dependencies: {
      '@neilmenday/stilo': 'github:neilmenday/stilo#main',
      react: '^18.0.0',
      'react-dom': '^18.0.0',
    },
    devDependencies: {
      '@storybook/react': '^8.0.0',
      '@storybook/react-webpack5': '^8.0.0',
      '@storybook/addon-essentials': '^8.0.0',
      '@types/react': '^18.0.0',
      '@types/react-dom': '^18.0.0',
      typescript: '^5.0.0',
    },
  };
  writeFile(path.join(targetDir, 'package.json'), JSON.stringify(pkg, null, 2));

  // tsconfig.json
  writeFile(path.join(targetDir, 'tsconfig.json'), JSON.stringify({
    compilerOptions: {
      target: 'ES2020',
      module: 'ESNext',
      moduleResolution: 'bundler',
      jsx: 'react-jsx',
      strict: true,
      declaration: true,
      outDir: 'dist',
      rootDir: 'src',
    },
    include: ['src'],
  }, null, 2));

  // systemsync.config.json
  const syncConfig: SystemSyncConfig = {
    extension: {
      name: extension.name,
      source: extension.source,
      componentsDir:    './src/components',
      componentSetsDir: './src/component-sets',
      workflowsDir:     './src/workflows',
      styleTilesDir:    './src/style-tiles',
      viewsDir:         './src/views',
      tokensFile:       './src/theme/tokens.ts',
    },
    figma: { fileKey: '' }, // filled in by generate command
    pages: {
      foundations:   '🧱 Foundations',
      passive:       '⚙️ Passive Components',
      componentSets: '🧩 Component Sets',
      workflows:     '⚡ Workflows',
      styleTiles:    '🪟 Style Tiles',
      views:         '📐 Views',
    },
  };
  writeFile(path.join(targetDir, 'systemsync.config.json'),
    JSON.stringify(syncConfig, null, 2));

  // .env.example
  writeFile(path.join(targetDir, '.env.example'),
    'FIGMA_TOKEN=your_figma_personal_access_token_here\n');

  // .gitignore
  writeFile(path.join(targetDir, '.gitignore'),
    'node_modules/\ndist/\n.env\n.DS_Store\n');

  // README.md
  writeFile(path.join(targetDir, 'README.md'), `
# ${extension.name}

A UI extension built on [${extension.source}](https://github.com/neilmenday/stilo)
using [SystemSync](https://github.com/neilmenday/stilo/packages/systemsync).

## Getting started

\`\`\`bash
npm install
npm run storybook
\`\`\`

## Figma sync

Add your Figma token to \`.env\` (see \`.env.example\`), then:

\`\`\`bash
npx @neilmenday/systemsync generate   # create Figma file from components
npx @neilmenday/systemsync compose    # read Figma compositions into code
npx @neilmenday/systemsync sync       # pull visual values from Figma
\`\`\`

## Chromatic (optional)

Connect this repo at chromatic.com for hosted visual review and regression testing.
`.trim());
}

function writeFile(filePath: string, content: string) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf-8');
}
